[book]
authors = ["Adrian Taylor", "Martin Brænne"]
language = "en"
multilingual = false
src = "src"
title = "cppfaq.rs"
[preprocessor]
[preprocessor.mermaid]
command = "mdbook-mermaid"
[output]
[output.html]
additional-js = ["third_party/mermaid/mermaid.min.js", "third_party/mermaid/mermaid-init.js"]
cname = "cppfaq.rs"
git-repository-url = "https://github.com/google/rust-design-faq"

[output.linkcheck]
follow-web-links = true
optional = true
