name: github pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: '0.4.10'
          # mdbook-version: 'latest'

      #- name: Install mdbook-linkcheck
        #run: |
          #curl -LSfs https://japaric.github.io/trust/install.sh | \
            #sh -s -- --git Michael-F-Bryan/mdbook-linkcheck
    
      - name: Install mdbook-mermaid
        run: |
          curl -LSfs https://japaric.github.io/trust/install.sh | \
            sh -s -- --git badboy/mdbook-mermaid
    
      - run: mdbook build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./book
          cname: cppfaq.rs
